config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'following/index', as: :following
  get 'followers/index', as: :followers
  get 'mentions/index', as: :mentions
  get 'recent_searchs/index', as: :recent_searchs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/twitter_request.rb
require "net/http"
require "uri"
class TwitterRequest
  def self.client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = "SfXfOwoQXJIz1tKAZky4ojZ2y"
      config.consumer_secret     = "P1CvPmqrOH0NriuTNU3rxulrMEbAp2M9tMl31pzBOHtm4OSgPR"
      config.access_token        = "1445083519236124674-VCVnFgTQKgNeUQG9Tv31ZnlOProLBC"
      config.access_token_secret = "MFBt5C0T5lVyanE5wl2eT3Z3KQ7d5HN6Uv5eD86aGOHBl"
    end
  end

  def self.following_me(search_params)
    followers = self.client.followers(search_params)
    followers.attrs[:users]
  end

  def self.timeline(search_params)

    user_timeline = self.client.user_timeline(search_params)
    user_timeline.pluck(:text)
  end

  def self.user(search_params)
    user = self.client.user(search_params)

    {
      user: user.name,
      location: user.location,
      favorites_count: user.favorites_count,
      followers_count: user.followers_count,
      friends_count: user.friends_count
    }
  end

  def self.mentions
    mentions_timeline = self.client.mentions_timeline
    mentions_timeline.pluck(:text)
  end

  def self.recent_searchs
    4.times.map do
      Faker::Lorem.paragraph
    end
  end

  def search(query = nil)

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    if params[:user_name].blank?
      params[:user_name] = 'Rodrigo35627393'
      @user = TwitterRequest.user(params[:user_name])
    end
  end
end

app/controllers/following_controller.rb
class FollowingController < ApplicationController
  def index
  end
end

app/controllers/mentions_controller.rb
class MentionsController < ApplicationController
  def index
  end
end

app/controllers/recent_searchs_controller.rb
class RecentSearchsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<% if @user %>
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header">
        
      </div>
      <div class="card-body">
        <ul class="list-group">
          <% TwitterRequest.following_me(params[:user_name]).each do |user| %>
          <li class="list-group-item"><%=link_to user[:name], root_path(user_name: user[:screen_name]) %></li>
          <% end %>
        </ul>
        <hr>
        <%=@user[:location]%>
        <button type="button" class="btn btn-primary position-relative">
          Favorites
          <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
            <%=@user[:favorites_count]%>
            <span class="visually-hidden">unread messages</span>
          </span>
        </button>

        <button type="button" class="btn btn-primary position-relative">
          Followers
          <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
            <%=@user[:followers_count]%>
            <span class="visually-hidden">unread messages</span>
          </span>
        </button>

        <button type="button" class="btn btn-primary position-relative">
          Friends count
          <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
            <%=@user[:friends_count]%>
            <span class="visually-hidden">unread messages</span>
          </span>
        </button>
      </div>
    </div>
  </div>
</div>
<hr>
<% end %>
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header">
        Who is following <%=params[:user_name]%>
      </div>
      <div class="card-body">
        <ul class="list-group">
          <% TwitterRequest.following_me(params[:user_name]).each do |user| %>
          <li class="list-group-item"><%=link_to user[:name], root_path(user_name: user[:screen_name]) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <div class="card-header">
        Timeline
      </div>
      <div class="card-body">
        <ul class="list-group">
          <% TwitterRequest.timeline(params[:user_name]).each do |text| %>
          <li class="list-group-item"><%= text %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<hr>
<div class="card">
  <div class="card-header">
    Last mentions
  </div>
  <div class="card-body">
    <ul class="list-group">
      <ul class="list-group">
        <% TwitterRequest.mentions.each do |text| %>
        <li class="list-group-item"><%= text %></li>
        <% end %>
      </ul>
    </ul>
  </div>
</div>
<hr>
<div class="card">
  <div class="card-header">
    Recent searchs
  </div>
  <div class="card-body">
    <ul class="list-group">
      <% 4.times do %>
      <li class="list-group-item"><%=Faker::Lorem.paragraph%></li>
      <% end %>
    </ul>
    <a href="<%=recent_searchs_path%>" class="btn btn-primary">Go to searchs</a>
  </div>
</div>

app/views/following/index.html.erb
<div class="card">
  <div class="card-header">
    Follwoing me
  </div>
  <div class="card-body">
    <ul>
      <% 10.times do %>
      <li><%=Faker::Twitter.user[:name]%></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%=root_path%>">Twitter Search RoR7</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%=root_path%>">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=following_path%>">Follwoing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=mentions_path%>">Mentions</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=recent_searchs_path%>">Recent searchs</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterSearchRor7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <main class="container">
      <%= render 'layouts/navbar' %>
      <hr>
      <%= yield %>
      <% console if Rails.env.development? %>
    </main>
  </body>
</html>

app/views/mentions/index.html.erb
<div class="card">
  <div class="card-header">
    Mentions
  </div>
  <div class="card-body">
    <ul>
      <% 10.times do %>
      <li><%=Faker::Twitter.user[:name]%></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/recent_searchs/index.html.erb
<div class="card">
  <div class="card-header">
    Recent searchs
  </div>
  <div class="card-body">
    <ul>
      <% 10.times do %>
      <li><%=Faker::Twitter.user[:name]%></li>
      <% end %>
    </ul>
  </div>
</div>